# Generated by Django 5.1 on 2024-10-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteText', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('colorR', models.IntegerField()),
                ('colorG', models.IntegerField()),
                ('colorB', models.IntegerField()),
            ],
        ),
    ]
