# Generated by Django 5.1 on 2024-10-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='pub_date',
            new_name='pubDate',
        ),
    ]
