# Generated by Django 5.1 on 2024-10-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_pub_date_note_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='noteTitle',
            field=models.TextField(default='No Title'),
            preserve_default=False,
        ),
    ]
