# Generated by Django 5.1 on 2024-10-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_note_notetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.TextField(default='No Category Specified'),
            preserve_default=False,
        ),
    ]
